import { Inter } from "next/font/google";
import "./globals.css";
import { ChakraProvider, Text } from '@chakra-ui/react';
 import SessionTimeoutModal from "./components/SessionTimeoutModal";
import { SessionTimeoutProvider } from "@/context/SessionTimeoutContext";
 
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ChakraProvider>
          <SessionTimeoutProvider>
            <Text>Header</Text>
            {children}
            <SessionTimeoutModal />
            <Text>Footer</Text>
          </SessionTimeoutProvider>
        </ChakraProvider>
      </body>
    </html>
  );
}
